### ISSUE TITLE
Make color of countries with connectivity data darker than countries with no conn data

### ISSUE THREAD

**Issue by narleras** [unicef/magicbox-maps#43]
![image](https://user-images.githubusercontent.com/6006052/36119022-d569ac36-100c-11e8-92b1-c3e7854edde4.png)

**Comment by mikefab** [comment]
![screen shot 2018-05-24 at 9 05 31 pm](https://user-images.githubusercontent.com/42814/40520821-3a1df474-5f96-11e8-97e6-10e0ef6e68eb.png)
