### ISSUE TITLE
Fix "file_lines" issue in react-app/src/public/lib.js

### ISSUE THREAD

**Issue by jflory7** [unicef/magicbox-maps#56]
File `lib.js` has 885 lines of code (exceeds 250 allowed). Consider refactoring.

https://codeclimate.com/github/unicef/magicbox-maps/react-app/src/public/lib.js#issue_5a866305a015730001000061

**Comment by mikefab** [comment]
That's a legacy file I was using while experimenting with webgl and react/redux. I will delete this. I will refactor all the webgl code out of MyMap.jsx and fix lint errors probably this weekend.

**Comment by jflory7** [comment]
@mikefab Awesome! For reference, if you are refactoring, here is the CodeClimate "report card" on MagicBox. Probably not possible to do all of this in a weekend, but the feedback might be helpful:

https://codeclimate.com/github/unicef/magicbox-maps/issues
