### ISSUE TITLE
Fix "similar-code" issue in react-app/src/components/WebglLayer.jsx

### ISSUE THREAD

**Issue by jwflory** [unicef/magicbox-maps#62]
Similar blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/unicef/magicbox-maps/react-app/src/components/WebglLayer.jsx#issue_5a8f90df77465f000100009f

**Comment by thoat** [comment]
As of 7/2018, the file `WebglLayer.jsx` no longer exists inside said directory.
