### ISSUE TITLE
Fix "identical-code" issue in react-app/src/public/lib.js

### ISSUE THREAD

**Issue by jwflory** [unicef/magicbox-maps#63]
Identical blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/unicef/magicbox-maps/react-app/src/public/lib.js#issue_5a8f90df77465f000100008e

**Comment by thoat** [comment]
I believe this no longer applies, since as of 7/2018 I don't see any a `public` directory inside `react-app/src`.
